---
- hosts: appubuntu
  vars_files:
    vars/app_ubuntu.yml
  # roles:
  #   - app
  tasks:
  - name: install pip
    apt:
      name: 
        - python3-pip
        - python3-setuptools
        - libmariadb-dev
      state: present
      update_cache: yes
  - name: Install the Python MySQLB module
    pip: name=mariadb   

  - name: upload app source
    copy:
      src: /etc/ansible/files/src/
      dest: ~/
