---
- hosts: appcentos
  vars_files:
    vars/app_centos.yml
  # roles:
  #   - app
  tasks:
  - name: install pip
    yum:
      name: 
        - python3-pip
        - python3-setuptools
        - gcc
        - python36-devel
        - MariaDB-shared 
        - MariaDB-devel
      state: present
      update_cache: yes
  - name: Install the Python MySQLB module
    pip: name=mariadb   

  - name: upload app source
    copy:
      src: /etc/ansible/files/src/
      dest: ~/